# docs: https://docs.rubocop.org/rubocop/

# inherit_from: .rubocop_todo.yml

# inherit_mode:
#   merge:
#     - Exclude

# require:
#   - rubocop-rubycw
#   - rubocop-rake
#   - rubocop-rspec
#   - rubocop-rails
#   - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - '.*/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'vendor/bundle/**/.*'
    - 'node_modules/**/*'


### Bundler

Bundler/OrderedGems: # https://docs.rubocop.org/rubocop/cops_bundler.html#bundlerorderedgems
  Enabled: false


### Layout

Layout/DotPosition: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutdotposition
  Enabled: false

Layout/EmptyLineAfterGuardClause: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylineafterguardclause
  Enabled: false

Layout/EmptyLines: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylines
  Enabled: false

Layout/EmptyLinesAroundClassBody: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundclassbody
  Enabled: false

Layout/EmptyLinesAroundMethodBody: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundmethodbody
  Enabled: false

Layout/EmptyLinesAroundModuleBody: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundmodulebody
  Enabled: false

Layout/EmptyLinesAroundBlockBody: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundblockbody
  Enabled: false

Layout/HashAlignment: # https://docs.rubocop.org/rubocop/cops_layout.html#layouthashalignment
  Enabled: false

Layout/LineLength: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutlinelength
  Max: 150
  Exclude:
    - '*.gemspec'

Layout/SpaceAroundEqualsInParameterDefault: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspacearoundequalsinparameterdefault
  Enabled: false

Layout/SpaceBeforeBlockBraces: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspacebeforeblockbraces
  Enabled: false

Layout/SpaceInLambdaLiteral: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinlambdaliteral
  Enabled: false

Layout/SpaceInsideBlockBraces: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsideblockbraces
  Enabled: false

Layout/SpaceInsideHashLiteralBraces: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsidehashliteralbraces
  Enabled: false

Layout/SpaceInsideRangeLiteral: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsiderangeliteral
  Enabled: false

Layout/SpaceInsideStringInterpolation: # https://docs.rubocop.org/rubocop/cops_layout.html#layoutspaceinsidestringinterpolation
  Enabled: false


### Lint

Lint/UnusedBlockArgument: # https://docs.rubocop.org/rubocop/cops_lint.html#lintunusedblockargument
  Enabled: false

Lint/UnusedMethodArgument: # https://docs.rubocop.org/rubocop/cops_lint.html#lintunusedmethodargument
  Enabled: false


### Metrics

Metrics/AbcSize: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsabcsize
  Max: 50

Metrics/BlockLength: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
  Max: 30
  CountAsOne: ['array', 'heredoc', 'method_call']
  Exclude:
    - 'app/admin/*'
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - 'spec/**/*'

Metrics/ClassLength: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsclasslength
  Max: 500
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/CyclomaticComplexity: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricscyclomaticcomplexity
  Max: 20

Metrics/MethodLength: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmethodlength
  Max: 15

Metrics/ModuleLength: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmodulelength
  Max: 500

Metrics/PerceivedComplexity: # https://docs.rubocop.org/rubocop/cops_metrics.html#metricsperceivedcomplexity
  Max: 22


### Naming

Naming/PredicateName: # https://docs.rubocop.org/rubocop/cops_naming.html#namingpredicatename
  Enabled: false

Naming/RescuedExceptionsVariableName: # https://docs.rubocop.org/rubocop/cops_naming.html#namingrescuedexceptionsvariablename
  Enabled: false
  # PreferredName: ex

Naming/VariableNumber: # https://docs.rubocop.org/rubocop/cops_naming.html#namingvariablenumber
  Enabled: false


### Style

Style/AsciiComments: # https://docs.rubocop.org/rubocop/cops_style.html#styleasciicomments
  Enabled: false

Style/BlockComments: # https://docs.rubocop.org/rubocop/cops_style.html#styleblockcomments
  Enabled: false

Style/ClassAndModuleChildren: # https://docs.rubocop.org/rubocop/cops_style.html#styleclassandmodulechildren
  Enabled: false

Style/CommandLiteral: # https://docs.rubocop.org/rubocop/cops_style.html#stylecommandliteral
  Enabled: false

Style/Documentation: # https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
  Enabled: false

Style/EmptyLambdaParameter: # https://docs.rubocop.org/rubocop/cops_style.html#styleemptylambdaparameter
  Enabled: false

Style/EmptyMethod: # https://docs.rubocop.org/rubocop/cops_style.html#styleemptymethod
  Enabled: false

Style/FrozenStringLiteralComment: # https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
  Enabled: false

Style/GuardClause: # https://docs.rubocop.org/rubocop/cops_style.html#styleguardclause
  Enabled: false

Style/IfUnlessModifier: # https://docs.rubocop.org/rubocop/cops_style.html#styleifunlessmodifier
  Enabled: false

Style/Lambda: # https://docs.rubocop.org/rubocop/cops_style.html#stylelambda
  Enabled: false

# Style/NumericLiterals: # https://docs.rubocop.org/rubocop/cops_style.html#stylenumericliterals
#   Enabled: false

Style/NumericPredicate: # https://docs.rubocop.org/rubocop/cops_style.html#stylenumericpredicate
  Enabled: false

# Style/PerlBackrefs: # https://docs.rubocop.org/rubocop/cops_style.html#styleperlbackrefs
#   Enabled: false

Style/PreferredHashMethods: # https://docs.rubocop.org/rubocop/cops_style.html#stylepreferredhashmethods
  Enabled: false

Style/RedundantAssignment: # https://docs.rubocop.org/rubocop/cops_style.html#styleredundantassignment
  Enabled: false

Style/RedundantInterpolation: # https://docs.rubocop.org/rubocop/cops_style.html#styleredundantinterpolation
  Enabled: false

Style/RedundantSelf: # https://docs.rubocop.org/rubocop/cops_style.html#styleredundantself
  Enabled: false

Style/RegexpLiteral: # https://docs.rubocop.org/rubocop/cops_style.html#styleregexpliteral
  Enabled: true
  EnforcedStyle: percent_r

Style/StringLiterals: # https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation: # https://docs.rubocop.org/rubocop/cops_style.html#stylestringliteralsininterpolation
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray: # https://docs.rubocop.org/rubocop/cops_style.html#stylesymbolarray
  Enabled: true

Style/TernaryParentheses: # https://docs.rubocop.org/rubocop/cops_style.html#styleternaryparentheses
  Enabled: false

Style/TrailingCommaInArguments: # https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainarguments
  Enabled: false

Style/TrailingCommaInArrayLiteral: # https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainarrayliteral
  Enabled: false

Style/TrailingCommaInHashLiteral: # https://docs.rubocop.org/rubocop/cops_style.html#styletrailingcommainhashliteral
  Enabled: false

Style/WordArray: # https://docs.rubocop.org/rubocop/cops_style.html#stylewordarray
  Enabled: false

Style/ZeroLengthPredicate: # https://docs.rubocop.org/rubocop/cops_style.html#stylezerolengthpredicate
  Enabled: false
