include_cookbook 'git'
include_cookbook 'vim'
include_cookbook 'tig'
include_cookbook 'tmux'
# include_cookbook 'anyenv'
# include_cookbook 'docker'
# include_cookbook 'mosh'
# include_cookbook 'ghq'
# include_cookbook 'zsh'
# include_cookbook 'peco'
# include_cookbook 'local-accounts'
# include_recipe 'ssh-agent'
